"""create core deployment models

Revision ID: 9faf4295a0db
Revises:
Create Date: 2026-09-14 04:25:41.167238
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9faf4295a0db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("repository_url", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "environments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("branch", sa.String(length=255), nullable=False),
        sa.Column(
            "dockerfile", sa.String(length=1024), server_default="Dockerfile", nullable=False
        ),
        sa.Column("build_context", sa.String(length=1024), server_default=".", nullable=False),
        sa.Column("container_port", sa.Integer(), nullable=False),
        sa.Column("container_name", sa.String(length=255), nullable=False),
        sa.Column(
            "docker_network", sa.String(length=255), server_default="web_network", nullable=False
        ),
        sa.Column("domain", sa.String(length=253), nullable=True),
        sa.Column("auto_deploy", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("latest_available_commit", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("container_port BETWEEN 1 AND 65535", name="ck_environment_port"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_name"),
        sa.UniqueConstraint("id", "project_id", name="uq_environment_id_project"),
        sa.UniqueConstraint("project_id", "name", name="uq_environment_project_name"),
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("environment_id", sa.Integer(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("commit_message", sa.Text(), nullable=True),
        sa.Column("image_name", sa.String(length=255), nullable=True),
        sa.Column("container_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED",
                "PREPARING",
                "FETCHING",
                "CHECKING_OUT",
                "BUILDING",
                "STOPPING_OLD",
                "STARTING",
                "VERIFYING",
                "SUCCESS",
                "FAILED",
                name="deployment_status",
            ),
            server_default="QUEUED",
            nullable=False,
        ),
        sa.Column(
            "trigger",
            sa.Enum("MANUAL", "WEBHOOK", "ROLLBACK", name="deployment_trigger"),
            nullable=False,
        ),
        sa.Column("failed_stage", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id", "project_id"],
            ["environments.id", "environments.project_id"],
            name="fk_deployment_environment_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployments_environment_id"), "deployments", ["environment_id"], unique=False
    )
    op.create_index(op.f("ix_deployments_project_id"), "deployments", ["project_id"], unique=False)
    op.create_index(op.f("ix_deployments_status"), "deployments", ["status"], unique=False)
    op.create_table(
        "environment_variables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("environment_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["environment_id"], ["environments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("environment_id", "key", name="uq_variable_environment_key"),
    )
    op.create_index(
        op.f("ix_environment_variables_environment_id"),
        "environment_variables",
        ["environment_id"],
        unique=False,
    )
    op.create_table(
        "deployment_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["deployment_id"], ["deployments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_logs_deployment_id"), "deployment_logs", ["deployment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deployment_logs_deployment_id"), table_name="deployment_logs")
    op.drop_table("deployment_logs")
    op.drop_index(
        op.f("ix_environment_variables_environment_id"), table_name="environment_variables"
    )
    op.drop_table("environment_variables")
    op.drop_index(op.f("ix_deployments_status"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_project_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_environment_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_table("environments")
    op.drop_table("users")
    op.drop_table("projects")
    sa.Enum(name="deployment_trigger").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="deployment_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
